AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.1
  Exclude:
  - 'specs/**/*'
  - 'vendor/**/*'
  - 'yard/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/LineLength:
  Max: 117

Style/PerlBackrefs:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%r': '{}'
