AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'
  - 'yard/**/*'

Layout/IndentHeredoc:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
