require: rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
  - 'vendor/**/*'
  - 'yard/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/MutableConstant:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
